alias:
  global:
    default: ""
    build: "&a■&r "
    lumirecia: "&6■&r "
    ressource: "&9■&r "
    uhc: "&c■&r "
    world: "&a■&r "
    zenga: "&6■&r "
  server:
    default: ""
    build: "&a> ■&r "
    lumirecia: "&6> ■&r "
    ressource: "&9> ■&r "
    uhc: "&c> ■&r "
    world: "&a> ■&r "
    zenga: "&6> ■&r "
prefix:
  live: "&5[LIVE] "
welcome_msg:
  server_connect: "&a%player% viens de rejoindre le serveur"
  server_disconnect: "&c%player% nous abandone"
  server_switch: "&7%player% : %old_serv_prefix% %old_serv_name% ▶ %new_serv_prefix% %new_serv_name%"
  server_new: "&dDisez bonjour a %player% ! s'est un nouvo"
group_info:
  omega: "Grade par défaut"
  omega+: "1er grade payant"
  sigma: "2nd grade payant"
  delta: "Développeur <3"
  beta: "Modérateur"
  beta+: "Chef modérateur"
  alpha: "Les dieux"